### Testes de rotas UserRoutes

# Criar usuário
# POST http://localhost:3000/users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDA3MTI1NCwiZXhwIjoxNzY0MTU3NjU0fQ.TImHX10OmQMyidALLOebqqYJ8Mexw2lnzaTfqiDsfiQ

# {
#   "name": "Membership teste",
#   "email": "testemembership.cruz@example.com",
#   "password": "senhatopzin123",
#   "role": "MEMBRO"
# }

# Login
# POST http://localhost:3000/login/auth
# Content-Type: application/json

# {
#   "email": "testemembership.cruz@example.com",
#   "password": "senhatopzin123"
# }

# GET http://localhost:3000/memberships
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDA3MTI1NCwiZXhwIjoxNzY0MTU3NjU0fQ.TImHX10OmQMyidALLOebqqYJ8Mexw2lnzaTfqiDsfiQ

## Listar todos os usuários
# GET http://localhost:3000/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2MzY3OTA1MywiZXhwIjoxNzYzNzY1NDUzfQ.Cp56WKWuFgueNGOkxq6e4TeJjbpjiout-KduwxBdFlA

### Restore User
# PATCH http://localhost:3000/users/eb4dd2cf-8aa2-4b37-8b86-1a6da9b03525/restore

### Paginação
# GET http://localhost:3000/users/pagination?page=1&pageSize=4

### Retorna por ID
# GET http://localhost:3000/users/4c5c84ff-f5e2-4a27-9563-03a9c97c3774
# Authorization: Bearer SEU_TOKEN_AQUI

### Update de usuário
# PUT http://localhost:3000/users/4a903605-f604-4518-8e5a-51431a987992
# Content-Type: application/json
#
# {
#   "name": "Ruan Pereira updated",
#   "email": "ruan.top@example.com",
#   "password": "senha12356786",
#   "role": "MEMBRO"
# }

# PUT http://localhost:3000/user/me
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYWEyOTIyYy1jY2FmLTQzMDgtYTViNi0wOTY0MTE0YTIyZmUiLCJyb2xlIjoiTUVNQlJPIiwiaWF0IjoxNzYzOTk4Mzg1LCJleHAiOjE3NjQwODQ3ODV9.KF0dVDxLMj24uE4Q5_WBBJFonq5uVmboZuyK9XcZwCA
# {
#     "name": "New Name"
# }

### Delete User
# DELETE http://localhost:3000/users/8f97dc4c-254d-40d3-9c9f-346a363d1e7b
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDAwMTAwMywiZXhwIjoxNzY0MDg3NDAzfQ.hd5RBKVvhggSeWp7gXIf1EWBJW35JViHMS51kEBoluo

### Criar Membership (Join Project)
# POST http://localhost:3000/memberships/join
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDA3MTQyMSwiZXhwIjoxNzY0MTU3ODIxfQ.Pj-cjikPzZ4bHXd7STFePHt8BH7rGnMstEj6tT2Un1w

# {
#   "userId": "3b4d6add-2513-41a6-ac18-38cad35afc6f",
#   "projectId": "28e38ea4-bde7-45b2-950d-3d375021a11d"
# }

# GET http://localhost:3000/memberships
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYWEyOTIyYy1jY2FmLTQzMDgtYTViNi0wOTY0MTE0YTIyZmUiLCJyb2xlIjoiTUVNQlJPIiwiaWF0IjoxNzYzNzUwNjEwLCJleHAiOjE3NjM4MzcwMTB9.woIGC_-9X_uiIttpvjDow8SyhKyvYfam5lmZXgMj1qY